### ISSUE TITLE
Question on running tests

### ISSUE THREAD

**Issue by AlexWang-16** [ArtskydJ/robotc-tap#1]
Hi Joseph, I'm interested in using this package to run tests for my robotC programs. I am new to RobotC, and as such, I have a few questions regarding how this works

1. Is it possible to run these tests locally on the computer before having to deploy to the robot? If so, how can I do this? My goal is to avoid having to spend time deploying the code to the robot to find out the test results.

2. If I take your example code and remove the calls to tFail(), I get a warning in RobotC that says "Unreferenced function tFail" when I compile the code. Should I be concerned about that? If so, how can I avoid this warning if I don't need to assert for failure?

**Comment by ArtskydJ** [comment]
### 1
I think there is a PC-based emulator.
https://www.vexforum.com/index.php/25504-robotc-emulator-console/0
 I would have to install RobotC to tell you how to use it, since I don't remember.

### 2
I didn't ever use this, so I never ran into that issue. :worried: This was a project I made when I was quitting robotics, and just starting to get into unit testing.

If it is a warning, then you can choose to ignore it. You don't have to run each and every function for this library to be useful.

To avoid the error/warning coming up at all, you could add this line to your tests:

```c
tFail("Avoid Unreferenced function tFail during compilation # SKIP");
```

The `# SKIP` will cause the library to skip the assertion. And the compiler will stop complaining about `tFail()` not getting called. However, if you do this, then you will see `# skipped 1` toward the end of the output.

You could also just delete the entire `tFail()` function from `tap.c`. It's not a necessary piece.
